import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

// POST /api/invite — Admin creates an invite
// 1. Validate admin is authenticated & is admin/owner of workspace
// 2. Generate secure token (DB default: 32-byte random hex)
// 3. Save with 24h expiry
// 4. Return invite details (token for email sending)
export async function POST(request: Request) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const body = await request.json()
  const { workspace_id, email } = body

  if (!workspace_id || !email) {
    return NextResponse.json({ error: 'workspace_id and email are required' }, { status: 400 })
  }

  // Validate email format
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  if (!emailRegex.test(email)) {
    return NextResponse.json({ error: 'Invalid email format' }, { status: 400 })
  }

  // Check: is user an admin/owner of this workspace?
  const { data: membership } = await supabase
    .from('workspace_members')
    .select('role')
    .eq('workspace_id', workspace_id)
    .eq('user_id', user.id)
    .single()

  if (!membership || !['owner', 'admin'].includes(membership.role)) {
    return NextResponse.json({ error: 'Only admins can send invites' }, { status: 403 })
  }

  // Check: is this email already a member?
  const { data: existingProfile } = await supabase
    .from('profiles')
    .select('id')
    .eq('email', email)
    .eq('is_deleted', false)
    .single()

  if (existingProfile) {
    const { data: existingMember } = await supabase
      .from('workspace_members')
      .select('user_id')
      .eq('workspace_id', workspace_id)
      .eq('user_id', existingProfile.id)
      .single()

    if (existingMember) {
      return NextResponse.json({ error: 'User is already a member of this workspace' }, { status: 409 })
    }
  }

  // Check: is there already a pending (unused, not expired) invite for this email?
  const { data: existingInvite } = await supabase
    .from('invites')
    .select('id')
    .eq('workspace_id', workspace_id)
    .eq('email', email)
    .eq('is_used', false)
    .gt('expires_at', new Date().toISOString())
    .single()

  if (existingInvite) {
    return NextResponse.json({ error: 'A pending invite already exists for this email' }, { status: 409 })
  }

  // Create the invite (token auto-generated by DB)
  const { data: invite, error } = await supabase
    .from('invites')
    .insert({
      workspace_id,
      email,
      created_by: user.id,
    })
    .select()
    .single()

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  // TODO: Send email with invite link when email service is configured
  // For now, return the token so admin can share the link manually

  return NextResponse.json({
    invite: {
      id: invite.id,
      email: invite.email,
      token: invite.token,
      expires_at: invite.expires_at,
      invite_link: `/invite/${invite.token}`,
    },
  })
}
